import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import styles from './page.module.css'
import clsx from "clsx";
import {Analytics} from '@vercel/analytics/next';

const inter = Inter({
    variable: "--font-inter-sans",
    subsets: ["latin", "cyrillic"],
    weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={clsx(inter.variable, styles.body)}>
        <Header/>
        {children}
        <Analytics />
    </body>
    </html>
  );
}
